<?xml version="1.0" encoding="utf-8"?><Database Name="Kviz" Class="QuizDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-1A67GIT;Initial Catalog=Kviz;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KvizConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Register" Method="Register">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
</Database>